export const languages = [
  { language: "English", short: "en-US" },
  { language: "Chinese", short: "zh-CN" },
  { language: "Cantonese", short: "zh-HK" },
  { language: "Bahasa Indonesia", short: "id-ID" },
  { language: "Russian", short: "ru-RU" },
  { language: "Japanese", short: "ja-JP" },
  { language: "Korean", short: "ko-KR" },
  { language: "French", short: "fr-FR" },
  { language: "Spanish", short: "es-ES" },
  { language: "Romanian", short: "ro-RO" },
  { language: "German", short: "de-DE" },
  { language: "Italian", short: "it-IT" },
  { language: "Dutch", short: "nl-NL" },
  { language: "Turkish", short: "tr-TR" },
  { language: "Hindi", short: "hi-IN" },
];

export const speechSynthesisLanguages = {
  "en-US": "en-US",
  "zh-CN": "zh-CN",
  "zh-HK": "zh-HK",
  "id-ID": "id-ID",
  "ru-RU": "ru-RU",
  "ja-JP": "ja-JP",
  "ko-KR": "ko-KR",
  "fr-FR": "fr-FR",
  "es-ES": "es-ES",
  "ro-RO": "ro-RO",
  "de-DE": "de-DE",
  "it-IT": "it-IT",
  "nl-NL": "nl-NL",
  "tr-TR": "tr-TR",
  "hi-IN": "hi-IN",
};
