export const languages = [
  { language: "English", short: "en-US" },
  { language: "Chinese (Simplified)", short: "zh-CN" },
  { language: "Chinese (Traditional)", short: "zh-TW" },
  { language: "Cantonese", short: "zh-HK" },
  { language: "Albanian", short: "sq-AL" },
  { language: "Arabic (Egypt)", short: "ar-EG" },
  { language: "Arabic (Saudi Arabia)", short: "ar-SA" },
  { language: "Bengali", short: "bn-IN" },
  { language: "Bulgarian", short: "bg-BG" },
  { language: "Croatian", short: "hr-HR" },
  { language: "Czech", short: "cs-CZ" },
  { language: "Danish", short: "da-DK" },
  { language: "Dutch", short: "nl-NL" },
  { language: "Estonian", short: "et-EE" },
  { language: "Filipino", short: "fil-PH" },
  { language: "Finnish", short: "fi-FI" },
  { language: "French", short: "fr-FR" },
  { language: "German", short: "de-DE" },
  { language: "Greek", short: "el-GR" },
  { language: "Gujarati", short: "gu-IN" },
  { language: "Hebrew", short: "he-IL" },
  { language: "Hindi", short: "hi-IN" },
  { language: "Hungarian", short: "hu-HU" },
  { language: "Indonesian", short: "id-ID" },
  { language: "Italian", short: "it-IT" },
  { language: "Japanese", short: "ja-JP" },
  { language: "Korean", short: "ko-KR" },
  { language: "Latvian", short: "lv-LV" },
  { language: "Lithuanian", short: "lt-LT" },
  { language: "Malay (Malaysia)", short: "ms-MY" },
  { language: "Malayalam", short: "ml-IN" },
  { language: "Marathi", short: "mr-IN" },
  { language: "Norwegian (Bokmål)", short: "nb-NO" },
  { language: "Pashto", short: "ps-AF" },
  { language: "Polish", short: "pl-PL" },
  { language: "Portuguese (Brazil)", short: "pt-BR" },
  { language: "Portuguese (Portugal)", short: "pt-PT" },
  { language: "Romanian", short: "ro-RO" },
  { language: "Russian", short: "ru-RU" },
  { language: "Serbian (Cyrillic)", short: "sr-RS" },
  { language: "Slovak", short: "sk-SK" },
  { language: "Slovenian", short: "sl-SI" },
  { language: "Spanish", short: "es-ES" },
  { language: "Swahili", short: "sw-KE" },
  { language: "Swedish", short: "sv-SE" },
  { language: "Tamil", short: "ta-IN" },
  { language: "Telugu", short: "te-IN" },
  { language: "Thai", short: "th-TH" },
  { language: "Turkish", short: "tr-TR" },
  { language: "Ukrainian", short: "uk-UA" },
  { language: "Vietnamese", short: "vi-VN" },
];

export const speechSynthesisLanguages = {
  "en-US": "en-US",
  "zh-CN": "zh-CN",
  "zh-TW": "zh-TW",
  "zh-HK": "zh-HK",
  "es-ES": "es-ES",
  "fr-FR": "fr-FR",
  "de-DE": "de-DE",
  "ru-RU": "ru-RU",
  "pt-BR": "pt-BR",
  "pt-PT": "pt-PT",
  "hi-IN": "hi-IN",
  "bn-IN": "bn-IN",
  "ja-JP": "ja-JP",
  "ko-KR": "ko-KR",
  "it-IT": "it-IT",
  "ar-EG": "ar-EG",
  "ar-SA": "ar-SA",
  "tr-TR": "tr-TR",
  "nl-NL": "nl-NL",
  "pl-PL": "pl-PL",
  "ro-RO": "ro-RO",
  "id-ID": "id-ID",
  "vi-VN": "vi-VN",
  "th-TH": "th-TH",
  "cs-CZ": "cs-CZ",
  "hu-HU": "hu-HU",
  "el-GR": "el-GR",
  "sv-SE": "sv-SE",
  "fi-FI": "fi-FI",
  "da-DK": "da-DK",
  "nb-NO": "nb-NO",
  "he-IL": "he-IL",
  "uk-UA": "uk-UA",
  "ms-MY": "ms-MY",
  "fil-PH": "fil-PH",
  "sk-SK": "sk-SK",
  "bg-BG": "bg-BG",
  "hr-HR": "hr-HR",
  "sr-RS": "sr-RS",
  "sl-SI": "sl-SI",
  "lt-LT": "lt-LT",
  "lv-LV": "lv-LV",
  "et-EE": "et-EE",
  "ml-IN": "ml-IN",
  "ta-IN": "ta-IN",
  "te-IN": "te-IN",
  "mr-IN": "mr-IN",
  "gu-IN": "gu-IN",
  "sw-KE": "sw-KE",
  "ps-AF": "ps-AF",
  "sq-AL": "sq-AL",
};
